name: LPHK-build
channels:
  - defaults
dependencies:
  - python=3.7*
  - pip
  - tk
  - pip:
    - pillow
    - pygame
    - pynput
    - tkcolorpicker
    - https://github.com/pyinstaller/pyinstaller/archive/develop.zip
    - py-getch
    - pyautogui
    - pywin32
    - pytesseract
    - imagehash
    - dhash
    - selenium
    - pyperclip
    - python-dateutil
    - launchpad-py
    - launchpad
